// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7S8rvlOgDGsT_wqrZ9A0a7cObmbwuiBs',
    appId: '1:94600198569:web:4425d45a6a732e1ebd6cb8',
    messagingSenderId: '94600198569',
    projectId: 'proyekagentdoctor',
    authDomain: 'proyekagentdoctor.firebaseapp.com',
    storageBucket: 'proyekagentdoctor.firebasestorage.app',
    measurementId: 'G-M0DW8DX9QK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQo6GKEikm8DBhpd3Bq4iKcbNyLOahv6U',
    appId: '1:94600198569:android:efc42a1458889e1fbd6cb8',
    messagingSenderId: '94600198569',
    projectId: 'proyekagentdoctor',
    storageBucket: 'proyekagentdoctor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo3N88QMKQ-YBGF9ytTZcRyaqa13cgVQU',
    appId: '1:94600198569:ios:b2317f92e37a9c74bd6cb8',
    messagingSenderId: '94600198569',
    projectId: 'proyekagentdoctor',
    storageBucket: 'proyekagentdoctor.firebasestorage.app',
    iosBundleId: 'com.example.agentDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo3N88QMKQ-YBGF9ytTZcRyaqa13cgVQU',
    appId: '1:94600198569:ios:b2317f92e37a9c74bd6cb8',
    messagingSenderId: '94600198569',
    projectId: 'proyekagentdoctor',
    storageBucket: 'proyekagentdoctor.firebasestorage.app',
    iosBundleId: 'com.example.agentDoctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7S8rvlOgDGsT_wqrZ9A0a7cObmbwuiBs',
    appId: '1:94600198569:web:4eb2e6fc54337bf1bd6cb8',
    messagingSenderId: '94600198569',
    projectId: 'proyekagentdoctor',
    authDomain: 'proyekagentdoctor.firebaseapp.com',
    storageBucket: 'proyekagentdoctor.firebasestorage.app',
    measurementId: 'G-BH9DP0QZBF',
  );
}
